import type { Metadata } from "next";
import { ThemeToggle } from "@/components/ThemeToggle";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.variable} font-sans antialiased`}>
        <div className="min-h-screen">
          <header className="fixed top-0 left-0 right-0 z-50 bg-transparent">
            <nav className="container mx-auto px-4 py-2 flex justify-end">
              <ThemeToggle />
            </nav>
          </header>
          <main className="pt-16">{children}</main>
        </div>
      </body>
    </html>
  );
}
